"""Per-domain Netscape cookie files for yt-dlp authentication."""

from __future__ import annotations

import re
import webbrowser
from pathlib import Path
from urllib.parse import urlparse

from frameforge.paths import cookies_dir, ensure_output_tree

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# This file was generated by FrameForge. Edit only if you know what you are doing.\n"
)

_SESSION_PROMPTED: set[str] = set()


def normalize_domain(host_or_url: str) -> str:
    text = (host_or_url or "").strip()
    if not text:
        raise ValueError("empty domain")
    if "://" not in text:
        text = "https://" + text
    parsed = urlparse(text)
    host = (parsed.hostname or "").lower().strip(".")
    if not host:
        raise ValueError(f"could not parse domain from {host_or_url!r}")
    if host.startswith("www."):
        host = host[4:]
    return host


def cookie_filename(domain: str) -> str:
    safe = re.sub(r"[^a-z0-9._-]+", "_", normalize_domain(domain))
    safe = safe.strip("._-") or "site"
    return f"{safe}.txt"


def cookie_path_for_domain(domain: str) -> Path:
    ensure_output_tree()
    return cookies_dir() / cookie_filename(domain)


def cookie_path_for_url(url: str) -> Path:
    return cookie_path_for_domain(normalize_domain(url))


def _is_cookie_data_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.lower().startswith("#httponly_"):
        stripped = stripped.split("_", 1)[-1]
    elif stripped.startswith("#"):
        return False
    return len(stripped.split("\t")) >= 6


def is_netscape_cookie_text(text: str) -> bool:
    """True when text looks like a non-empty Netscape cookies.txt with at least one cookie."""
    if not text or not str(text).strip():
        return False
    return any(_is_cookie_data_line(line) for line in str(text).splitlines())


def has_cookies(domain_or_url: str) -> bool:
    path = cookie_path_for_url(domain_or_url) if "://" in domain_or_url else cookie_path_for_domain(domain_or_url)
    if not path.is_file() or path.stat().st_size <= 0:
        return False
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
    return is_netscape_cookie_text(text)


def should_skip_auth_prompt(domain_or_url: str) -> bool:
    """Smart skip: existing cookie file OR already prompted this process session."""
    domain = normalize_domain(domain_or_url)
    if has_cookies(domain):
        return True
    return domain in _SESSION_PROMPTED


def mark_session_prompted(domain_or_url: str) -> None:
    _SESSION_PROMPTED.add(normalize_domain(domain_or_url))


def clear_session_prompts() -> None:
    _SESSION_PROMPTED.clear()


def ensure_cookie_stub(domain: str) -> Path:
    """Create an empty Netscape cookie file shell if missing."""
    path = cookie_path_for_domain(domain)
    if not path.exists():
        path.write_text(NETSCAPE_HEADER, encoding="utf-8")
    return path


def import_netscape_cookies(domain: str, source: Path) -> Path:
    """Copy a Netscape cookies.txt into the FrameForge cookies folder for domain.

    Rejects empty or non-Netscape files. Existing domain files are replaced
    (import-to-replace) after validation.
    """
    source = Path(source)
    if not source.is_file():
        raise FileNotFoundError(source)
    text = source.read_text(encoding="utf-8", errors="ignore")
    if not is_netscape_cookie_text(text):
        raise ValueError(
            "Not a valid Netscape cookies.txt (empty or no cookie rows). "
            "Export cookies with a browser extension, then import again."
        )
    dest = cookie_path_for_domain(domain)
    dest.write_text(text, encoding="utf-8")
    mark_session_prompted(domain)
    return dest


def open_site_for_login(url_or_domain: str) -> str:
    """Open the system browser to the site so the user can log in / accept gates.

    Returns the normalized domain. After login, the user should export cookies
    (e.g. via a browser extension) to a Netscape cookies.txt and import them
    with import_netscape_cookies / the GUI Authenticate flow.
    """
    domain = normalize_domain(url_or_domain)
    url = url_or_domain.strip()
    if "://" not in url:
        url = f"https://{domain}/"
    webbrowser.open(url)
    mark_session_prompted(domain)
    ensure_cookie_stub(domain)
    return domain


def resolve_cookiefile_for_url(url: str) -> Path | None:
    """Return cookiefile path for yt-dlp if present and Netscape-valid."""
    path = cookie_path_for_url(url)
    if has_cookies(url):
        return path
    return None
